services:
  json:
    build:
      context: .
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME:?}
        - USER_NAME=${FRONTEND_USER_NAME:?}
    volumes:
      - .:/home/${FRONTEND_USER_NAME:?}/${COMPOSE_PROJECT_NAME:?}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8000:8000

