import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from "../styles/Home.module.css"
import { getPostsData } from '../lib/post'  // 追記


// SSGのための記述
export async function getStaticProps() {
  // データの取得先を指定
  const allPostsData = getPostsData();  // id, title, date, thumbnail のpathが格納されている
// 以下のように記述することでallPostsDataをHomeにpropsとして渡すことができるようになる。
  return {
    props: {
      allPostsData,
    }
  };
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Sample App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.main}>
          <h1>
            Welcome to
            <Link href="/posts/samplePost">
              <a> Sample App!!</a>
            </Link>
          </h1>
            {/* map関数で受け取ったデータを出力する */}
            {allPostsData.map(({id, title, thumbnail}) => (
              <article key={id}>
                <Link href={`/posts/${id}`}>
                  <Image
                    src={`${thumbnail}`}
                    width={500} height={500}
                    objectFit="contain"
                  />
                </Link>
                <Link href={`/posts/${id}`}>
                  <a className={styles.title}>{title}</a>
                </Link>
              </article>
            ))}
        </div>
    </>
  )
}
